/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadoradeveiculo.telas;

import Util.TableCellRendererColor;
import Util.ValidadorCPFECNPJ;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

/**
 *
 * @author Michel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    List<Usuario> listaUsuario = new ArrayList<>();

    public TelaPrincipal() {
        initComponents();
        JTBUsuario.setDefaultRenderer(Object.class, new TableCellRendererColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFCNPJ = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        JBCPF = new javax.swing.JButton();
        JBCNPJ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTBUsuario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            JTFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCPFFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("<html>CPF: <font color=\"red\"><b>*</b></font>");

        try {
            JTFCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFCNPJ.setToolTipText("Digite só números");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("CNPJ:");

        JBCPF.setText("CPF");
        JBCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCPFActionPerformed(evt);
            }
        });

        JBCNPJ.setText("CNPJ");
        JBCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCNPJActionPerformed(evt);
            }
        });

        JTBUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JTBUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTBUsuario);

        jButton1.setText("Pesquisa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(JBCNPJ))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(JBCPF)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCPF))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCNPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCPFActionPerformed
        verificarCPF();
    }//GEN-LAST:event_JBCPFActionPerformed

    private void JBCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCNPJActionPerformed
        try {
            String cnpj = JTFCNPJ.getText();
            System.out.println("cnpj " + cnpj);

            if (cnpj.equals("  .   .   /    -  ")) {
                System.out.println("vazio");
            } else {
                ValidadorCPFECNPJ v = new ValidadorCPFECNPJ();
                Boolean existe = v.validaCNPJ(cnpj);
                if (existe == false) {
                    JOptionPane.showMessageDialog(null, "CNPJ inválido.", "ERRO!!!", 0);
                } else {
                    System.out.println("existe " + existe);
                }
            }

        } catch (HeadlessException e) {
            System.out.println("Erro JBCNPJActionPerformed " + e.getMessage());
        }
    }//GEN-LAST:event_JBCNPJActionPerformed

    private void JTFCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCPFFocusLost
        verificarCPF();
    }//GEN-LAST:event_JTFCPFFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            SQL.Usuario.Pesquisar p = new SQL.Usuario.Pesquisar();
            listaUsuario = p.todosOsUsuarios();
            preencherTabelaUsuario();
        } catch (SQLException e) {
            System.out.println("Erro jButton1ActionPerformed " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void preencherTabelaUsuario() {
        DefaultTableModel modelo = (DefaultTableModel) JTBUsuario.getModel();

        //reordenar colunas
        JTBUsuario.getTableHeader().setReorderingAllowed(false);
        //ordena linhas pelo título da coluna
        JTBUsuario.setAutoCreateRowSorter(true);

        JTBUsuario.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTBUsuario.getColumnModel().getColumn(0).setPreferredWidth(100);
        modelo.setRowCount(0);

        if (listaUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não existe nenhum dado.", "Atenção!!!", 1);
        } else {
            listaUsuario.forEach((d) -> {
                modelo.addRow(new Object[]{
                    d.getNome(), d.getEmail()
                });
            });
        }
    }

    public void verificarCPF() {
        try {
            String cpf = JTFCPF.getText();
            System.out.println("cpf " + cpf);

            if (cpf.equals("   .   .   -  ")) {
                JOptionPane.showMessageDialog(null, "CPF inválido.", "ERRO!!!", 0);
            } else {
                ValidadorCPFECNPJ v = new ValidadorCPFECNPJ();
                Boolean existe = v.validaCPF(cpf);
                if (existe == false) {
                    JOptionPane.showMessageDialog(null, "CPF inválido.", "ERRO!!!", 0);
                } else {
                    System.out.println("existe " + existe);
                }
            }

        } catch (HeadlessException e) {
            System.out.println("Erro JBCPFActionPerformed " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCNPJ;
    private javax.swing.JButton JBCPF;
    private javax.swing.JTable JTBUsuario;
    private javax.swing.JFormattedTextField JTFCNPJ;
    private javax.swing.JFormattedTextField JTFCPF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
